apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: umbrella-gateway
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "service-b.local"
