apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
    defaultProviders:
      metrics:
      - prometheus
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
    meshNetworks: 'networks: {}'
    extensionProviders:
      - name: ftb-ext-authz-grpc
        envoyExtAuthzGrpc:
          service: "ftb-kangaroo.ftb.svc.cluster.local"
          port: "2020"
          timeout: "1s"
