apiVersion: v2
name: umbrella
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "0.16.5"
    repository: "https://ot-container-kit.github.io/helm-charts/"
    condition: redis.enabled

  - name: service-template
    version: "0.1.0"
    repository: file://../service-template
    alias: service-a
    condition: service-a.enabled

  - name: service-template
    version: "0.1.0"
    repository: file://../service-template
    alias: service-b
    condition: service-b.enabled

  - name: service-template
    version: "0.1.0"
    repository: file://../service-template
    alias: service-c
    condition: service-c.enabled
