apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ftb-stage
  namespace: argocd
spec:
  project: ftb
  source:
    repoURL: ghcr.io/fliptheboard
    chart: ftb
    targetRevision: 0.1.0-67246882c859
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ftb-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
