apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella
  namespace: argocd
spec:
  project: umbrella
  source:
    repoURL: ghcr.io/mrdan4es/bazel-argocd-grpc-example
    chart: umbrella
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: umbrella
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
