apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda-operator
  namespace: argocd
spec:
  project: redpanda
  source:
    repoURL: https://charts.redpanda.com
    chart: operator
    targetRevision: v25.1.3
    helm:
      values: |
        crds:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: redpanda-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
